//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#pragma once

#include "XamlBindingInfo.xaml.g.h"

namespace winrt::GameHost::implementation
{
    using IInspectable = ::winrt::Windows::Foundation::IInspectable;

    template <typename D, typename ... I>
    struct MainPageT : public ::winrt::GameHost::implementation::MainPage_base<D,
        ::winrt::Windows::UI::Xaml::Markup::IComponentConnector,
        ::winrt::Windows::UI::Xaml::Markup::IComponentConnector2,
        I...>
    {
        using base_type = typename MainPageT::base_type;
        using base_type::base_type;
        using class_type = typename MainPageT::class_type;

        void InitializeComponent();
        void Connect(int32_t connectionId, IInspectable const& target);
        ::winrt::Windows::UI::Xaml::Markup::IComponentConnector GetBindingConnector(int32_t connectionId, IInspectable const& target);
        void UnloadObject(::winrt::Windows::UI::Xaml::DependencyObject const& dependencyObject);
        void DisconnectUnloadedObject(int32_t connectionId);

        ::winrt::Windows::UI::Xaml::Controls::ListView GamelistView()
        {
            return _GamelistView;
        }
        void GamelistView(::winrt::Windows::UI::Xaml::Controls::ListView value)
        {
            _GamelistView = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::Image GamePhoto()
        {
            return _GamePhoto;
        }
        void GamePhoto(::winrt::Windows::UI::Xaml::Controls::Image value)
        {
            _GamePhoto = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::TextBlock GameTitle()
        {
            return _GameTitle;
        }
        void GameTitle(::winrt::Windows::UI::Xaml::Controls::TextBlock value)
        {
            _GameTitle = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::TextBlock GameSubtitle()
        {
            return _GameSubtitle;
        }
        void GameSubtitle(::winrt::Windows::UI::Xaml::Controls::TextBlock value)
        {
            _GameSubtitle = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::RatingControl GameRating()
        {
            return _GameRating;
        }
        void GameRating(::winrt::Windows::UI::Xaml::Controls::RatingControl value)
        {
            _GameRating = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::TextBlock GameDescription()
        {
            return _GameDescription;
        }
        void GameDescription(::winrt::Windows::UI::Xaml::Controls::TextBlock value)
        {
            _GameDescription = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::Button buttonPlay()
        {
            return _buttonPlay;
        }
        void buttonPlay(::winrt::Windows::UI::Xaml::Controls::Button value)
        {
            _buttonPlay = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::AppBarButton buttonRunLocal()
        {
            return _buttonRunLocal;
        }
        void buttonRunLocal(::winrt::Windows::UI::Xaml::Controls::AppBarButton value)
        {
            _buttonRunLocal = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::AppBarButton buttonPublish()
        {
            return _buttonPublish;
        }
        void buttonPublish(::winrt::Windows::UI::Xaml::Controls::AppBarButton value)
        {
            _buttonPublish = value;
        }

        ::winrt::Windows::UI::Xaml::Controls::AppBarButton buttonVisit()
        {
            return _buttonVisit;
        }
        void buttonVisit(::winrt::Windows::UI::Xaml::Controls::AppBarButton value)
        {
            _buttonVisit = value;
        }
        
         ::winrt::com_ptr<::winrt::GameHost::implementation::XamlBindings> Bindings;

    protected:
        bool _contentLoaded{false};

    private:
        struct MainPage_obj2_Bindings;
        struct MainPage_obj1_Bindings;

        ::winrt::Windows::UI::Xaml::Controls::ListView _GamelistView{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::Image _GamePhoto{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::TextBlock _GameTitle{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::TextBlock _GameSubtitle{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::RatingControl _GameRating{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::TextBlock _GameDescription{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::Button _buttonPlay{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::AppBarButton _buttonRunLocal{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::AppBarButton _buttonPublish{nullptr};
        ::winrt::Windows::UI::Xaml::Controls::AppBarButton _buttonVisit{nullptr};
    };
}

